language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .
  - pip install -r requirements.txt
before_script:
  - flake8 | lintly
script:
  - coverage run -m pytest
after_success:
  - codecov
