language: python

jobs:
  include:
    - stage: lint
      script: flake8 | lintly
      install:
        - pip install -e .
        - pip install -r requirements.txt
    - stage: test
      script: coverage run -m pytest
      python:
        - 2.7
        - 3.4
        - 3.5
        - 3.6
      install:
        - pip install -e .
        - pip install -r requirements.txt
      after_success:
        - codecov

stages:
  - lint
  - test
