language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -e .
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script: flake8 | lintly --log
    - stage: test
      script: coverage run -m pytest
      after_success:
        - codecov

stages:
  - lint
  - test
